repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      - id: ruff
        name: ruff-lint
        args: [--fix]
      - id: ruff
        name: ruff-sort
        args: ["--select", "I", "--fix"]
      - id: ruff-format
        name: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.394
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.1
    hooks:
      - id: uv-lock
